sudo: false

branches:
  except:
    - gh-pages

language: python
python:
  - 2.7

env:
  - PEBBLE_SDK_VERSION=3.14
  - PEBBLE_SDK_VERSION=latest

before_install:
  - nvm install 0.12
  - nvm use 0.12
  - wget https://github.com/pebble/pebble-tool/releases/download/v4.2.1/pebble-sdk-4.2.1-linux64.tar.bz2
  - mkdir -p ~/.pebble-sdk
  - tar -jxf pebble-sdk-* -C ~/.pebble-sdk
  - touch ~/.pebble-sdk/ENABLE_ANALYTICS
  - export PEBBLE_SDK=~/.pebble-sdk/pebble-sdk-*
  - export PEBBLE=$PEBBLE_SDK/bin/pebble
  - export PATH="$PATH:$(npm config get prefix)/.bin"

install:
  - pushd $PEBBLE_SDK
  - virtualenv --no-site-packages .env
  - source .env/bin/activate
  - pip install -r requirements.txt
  - deactivate
  - popd
  - $PEBBLE sdk set-channel beta
  - yes | $PEBBLE sdk install $PEBBLE_SDK_VERSION
  - npm install --only=dev

script:
  - jshint --verbose --show-non-errors src/*.js
  - npm test
  - sed -i "s/__WMATA_API_KEY__/$WMATA_API_KEY/" src/urls.js
  - mkdir -p src/js/
  - mv src/*.js src/js/
  - git clone --single-branch https://github.com/pebble/pebblejs pebblejs
  - cp -a -n pebblejs/{resources,src,waftools,wscript} .
  - $PEBBLE build

deploy:
  provider: releases
  api_key: $GITHUB_DEPLOY_KEY
  skip_cleanup: true
  file: build/wmata-with-you.pbw
  on:
    tags: true
