sudo: false

branches:
  except:
    - gh-pages

language: python
python:
  - "2.7"
node_js:
  - "0.12"

env:
  - PEBBLE_SDK_VERSION=3.9

before_install:
  - wget https://github.com/pebble/pebble-tool/releases/download/v4.0-rc5/pebble-sdk-4.0-rc5-linux64.tar.bz2?source=travis
  - mkdir -p ~/.pebble-sdk
  - tar -jxf pebble-sdk-* -C ~/.pebble-sdk
  - touch ~/.pebble-sdk/ENABLE_ANALYTICS
  - export PEBBLE_SDK=~/.pebble-sdk/pebble-sdk-*
  - export PEBBLE=$PEBBLE_SDK/bin/pebble

install:
  - pushd $PEBBLE_SDK
  - virtualenv --no-site-packages .env
  - source .env/bin/activate
  - pip install -r requirements.txt
  - deactivate
  - popd
  - $PEBBLE sdk set-channel beta
  - yes | $PEBBLE sdk install $PEBBLE_SDK_VERSION
  - mkdir -p src/js/
  - mv src/*.js src/js/
  - git clone --single-branch https://github.com/pebble/pebblejs
  - cp -anv pebblejs/{resources,src,waftools,wscript} .
  - npm install -g jshint mocha chai

script:
  - jshint src/js/*.js
#  - mocha test/tests.js
  - $PEBBLE build

after_script:
  - git clean -fd

