sudo: false

language: python
python:
  - "2.7"

env:
  - PEBBLE_SDK_VERSION=4.0.1

branches:
  except:
    - gh-pages

before_install:
  - wget https://github.com/pebble/pebble-tool/archive/v4.4.1.tar.gz?source=travis
  - mkdir -p ~/.pebble-sdk
  - tar -jxf pebble-sdk-* -C ~/.pebble-sdk
  - touch ~/.pebble-sdk/ENABLE_ANALYTICS
  - export PEBBLE_SDK=~/.pebble-sdk/pebble-sdk-*
  - export PEBBLE=$PEBBLE_SDK/bin/pebble

install:
  - pushd $PEBBLE_SDK
  - virtualenv --no-site-packages .env
  - source .env/bin/activate
  - pip install -r requirements.txt
  - deactivate
  - popd
  - $PEBBLE sdk set-channel beta
  - yes | $PEBBLE sdk install $PEBBLE_SDK_VERSION
  - git clone --single-branch https://github.com/pebble/pebblejs
  - cp -anv pebblejs/{resources,src,waftools,wscript} .

script:
  - $PEBBLE build

after_script:
  - git clean -fd

